run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gofmt

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - source: "^//go:generate "
      linters:
        - typecheck
  exclude-generated: strict

output:
  formats:
    - format: colored-line-number
  sort-results: true
  sort-order:
    - linter
    - severity
    - file
