version: 2

builds:
  - main: .
    binary: slacko
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

brews:
  - name: slacko
    repository:
      owner: m96-chan
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/m96-chan/Slacko
    description: A lightweight, keyboard-driven TUI client for Slack
    license: MIT
    install: |
      bin.install "slacko"

aurs:
  - name: slacko-bin
    homepage: https://github.com/m96-chan/Slacko
    description: A lightweight, keyboard-driven TUI client for Slack
    maintainers:
      - "m96-chan"
    license: MIT
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/slacko-bin.git"
    package: |
      install -Dm755 slacko "${pkgdir}/usr/bin/slacko"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
